# Generated by Django 4.1.7 on 2023-03-23 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ALL', 'ALL'), ('WORK', 'WORK'), ('PERSONAL', 'PERSONAL'), ('WHISLIST', 'WHISLIST'), ('BIRTHDAY', 'BIRTHDAY'), ('HABITS', 'HABITS'), ('LEARNING', 'LEARNING')], default='ALL', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(auto_now=True)),
                ('completionstatus', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=400)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_app.category')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
