# Generated by Django 4.1.7 on 2023-03-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completionstatus',
            field=models.CharField(max_length=255),
        ),
    ]
