# Generated by Django 3.2.18 on 2023-03-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_app', '0002_alter_task_completionstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='completionstatus',
            field=models.CharField(choices=[('ON GOING', 'ON GOING'), ('DONE', 'DONE')], max_length=255),
        ),
    ]
