# Generated by Django 4.1.7 on 2023-03-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_app', '0003_auto_20230327_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='orange', max_length=150),
        ),
    ]
